import { Button, Flex, Text, Box, Tabs, TabList, Tab, TabPanels, TabPanel } from "@chakra-ui/react"
import Head from "next/head"
import { useMoralis } from "react-moralis"
import Header from "../components/Header"
import Profile from "../components/Profile"
import Balance from "../components/Balance";
import Transactions from "../components/Transactions";
import NFTs from "../components/NFTs";
import SendETH from "../components/SendETH";


export default function Home() {
  const { isAuthenticated, authenticate, isAuthenticating, user, logout, isLoggingOut } = useMoralis()
  if (!isAuthenticated) {
    return (
      <>
        <Head>
          <title>Login | Dashboard</title>
        </Head>

        <Flex
          direction='column'
          justifyContent='center'
          alignItems='center'
          width='100vw'
          height='100vh'
          bgGradient="linear(to-br, teal.400, purple.300)"
        >
          <Text fontSize="5xl" fontWeight='bold' color='white'>
            CBDC Recipient Dashboard
          </Text>
          <Button colorScheme="purple" size='lg' mt='6'
            onClick={() => authenticate({ signingMessage: "Sigining to Metamask" })} disabled={isAuthenticating}>Login with Metamask</Button>
        </Flex>
      </>
    )
  }

  return (

    <>
      <Head>
        <title>Recipient Dashboard</title>
      </Head>

      <Flex direction='column' width='100vw' height='100vh'>

        <Header user={user} logout={logout} isLoggingOut={isLoggingOut} />
        <Box flex='1' bg='purple.100' px='44' py='20'>
          <Tabs size='lg' colorScheme='purple'>
            <TabList>
              <Tab fontWeight='bold'>Profile</Tab>
              <Tab fontWeight='bold'>Balance</Tab>
              <Tab fontWeight='bold'>Transactions</Tab>
              <Tab fontWeight='bold'>NFTs</Tab>
              <Tab fontWeight='bold'>Send ETH</Tab>
            </TabList>

            <TabPanels>
              <TabPanel><Profile user={user}></Profile></TabPanel>
              <TabPanel><Balance user={user} /></TabPanel>
              <TabPanel><Transactions user={user} /></TabPanel>
              <TabPanel><NFTs user={user} /></TabPanel>
              <TabPanel><SendETH user={user} /></TabPanel>

            </TabPanels>
          </Tabs>
        </Box>

      </Flex>
    </>
  )
}


// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
